apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: default

  # Source of the application manifests
  source:
    repoURL: hhttps://github.com/Endrit-Selita/Excalidraw-EKS
    targetRevision: HEAD  # For Helm, this refers to the chart version.
    path: app-hub

  # Destination cluster and namespace to deploy the application
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc
    namespace: apps
  
  syncPolicy:
    automated:
      enabled: true
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.